sudo: required
services:
  - docker

before_install:
  - docker build -t uthredsonofuthred/docker-react -f Dockerfile.dev .

script:
  - docker run uthredsonofuthred/docker-react npm run test -- --coverage
